/** ShinyMetal Foundry — Tailwind CSS preset.
 *  Every value points at a CSS custom property from tokens.css, so light/dark
 *  switching is `<html data-theme="dark">` and never a Tailwind `dark:` variant.
 *  Usage:  // tailwind.config.js
 *          module.exports = { presets: [require('./tailwind/preset.js')], content: [...] }
 *  Load tokens.css (generated by the system) before your own stylesheet.
 */
module.exports = {
  theme: {
    colors: {
      "surface": "var(--surface)",
      "surface-raised": "var(--surface-raised)",
      "surface-sunken": "var(--surface-sunken)",
      "ink": "var(--ink)",
      "ink-2": "var(--ink-2)",
      "ink-3": "var(--ink-3)",
      "rule": "var(--rule)",
      "rule-strong": "var(--rule-strong)",
      "metal": "var(--metal)",
      "metal-bright": "var(--metal-bright)",
      "metal-tint": "var(--metal-tint)",
      "on-metal": "var(--on-metal)",
      "link": "var(--link)",
      "focus": "var(--focus)",
      "claim-shipped": "var(--claim-shipped)",
      "claim-shipped-tint": "var(--claim-shipped-tint)",
      "claim-preorder": "var(--claim-preorder)",
      "claim-preorder-tint": "var(--claim-preorder-tint)",
      "claim-promise": "var(--claim-promise)",
      "claim-promise-tint": "var(--claim-promise-tint)",
      "claim-rumor": "var(--claim-rumor)",
      "claim-rumor-tint": "var(--claim-rumor-tint)",
      "claim-research": "var(--claim-research)",
      "claim-research-tint": "var(--claim-research-tint)",
      "signal-ok": "var(--signal-ok)",
      "signal-ok-tint": "var(--signal-ok-tint)",
      "signal-warn": "var(--signal-warn)",
      "signal-warn-tint": "var(--signal-warn-tint)",
      "signal-danger": "var(--signal-danger)",
      "signal-danger-tint": "var(--signal-danger-tint)",
      "signal-neutral": "var(--signal-neutral)",
      "signal-neutral-tint": "var(--signal-neutral-tint)"
},
    spacing: {
      "1": "var(--space-1)",
      "2": "var(--space-2)",
      "3": "var(--space-3)",
      "4": "var(--space-4)",
      "5": "var(--space-5)",
      "6": "var(--space-6)",
      "7": "var(--space-7)",
      "8": "var(--space-8)",
      "9": "var(--space-9)"
},
    borderRadius: {
      "0": "var(--radius-0)",
      "sm": "var(--radius-sm)",
      "md": "var(--radius-md)",
      "full": "var(--radius-full)"
},
    boxShadow: {
      "lift": "var(--shadow-lift)",
      "pop": "var(--shadow-pop)"
},
    fontFamily: {
      "display": [
            "\"Fraunces\", \"Iowan Old Style\", Georgia, serif"
      ],
      "body": [
            "\"Newsreader\", \"Iowan Old Style\", Georgia, serif"
      ],
      "data": [
            "\"IBM Plex Mono\", \"SFMono-Regular\", Menlo, monospace"
      ]
},
    extend: {
      screens: { 'xs': '390px', 'sm': '640px', 'md': '768px', 'lg': '1024px', 'xl': '1200px' },
      maxWidth: { 'measure': '68ch', 'page': '1120px' },
    },
  },
  plugins: [
    function ({ addComponents }) {
      // one utility class per type style, mirroring tokens.css
      addComponents({
        ".fd-display-xl": { fontFamily: "var(--font-display)", fontSize: "44px", lineHeight: "46px", fontWeight: "600" }, ".fd-display-lg": { fontFamily: "var(--font-display)", fontSize: "32px", lineHeight: "36px", fontWeight: "600" }, ".fd-display-md": { fontFamily: "var(--font-display)", fontSize: "24px", lineHeight: "28px", fontWeight: "600" }, ".fd-display-sm": { fontFamily: "var(--font-display)", fontSize: "19px", lineHeight: "24px", fontWeight: "600" }, ".fd-body-lg": { fontFamily: "var(--font-body)", fontSize: "19px", lineHeight: "30px", fontWeight: "400" }, ".fd-body": { fontFamily: "var(--font-body)", fontSize: "17px", lineHeight: "26px", fontWeight: "400" }, ".fd-body-sm": { fontFamily: "var(--font-body)", fontSize: "15px", lineHeight: "22px", fontWeight: "400" }, ".fd-caption": { fontFamily: "var(--font-body)", fontSize: "13px", lineHeight: "18px", fontWeight: "400" }, ".fd-eyebrow": { fontFamily: "var(--font-data)", fontSize: "12px", lineHeight: "16px", fontWeight: "500" }, ".fd-data": { fontFamily: "var(--font-data)", fontSize: "14px", lineHeight: "20px", fontWeight: "400" }, ".fd-data-lg": { fontFamily: "var(--font-data)", fontSize: "20px", lineHeight: "24px", fontWeight: "500" }, ".fd-data-xl": { fontFamily: "var(--font-data)", fontSize: "32px", lineHeight: "36px", fontWeight: "500" }
      });
    },
  ],
};
